DynamoRIO/drmemory

- .appveyor.yml
- .travis.yml
- tests/CMakeLists.txt
- tests/runsuite.cmake
- tests/runsuite_wrapper.pl
Adds an initial attempt at an AppVeyor configuration file, based on
DynamoRIO's.  We do a build-only with VS2010 and full tests with VS2013.
> i#1938: initial AppVeyor config

- CMakeLists.txt
- common/utils.h
- drltrace/CMakeLists.txt
- drltrace/README.md
- drltrace/drltrace.c
- drltrace/drltrace.dox
- drltrace/drltrace_frontend.cpp
- drmemory/replace.c
- drstrace/CMakeLists.txt
- make/resources.rc
- tests/runsuite_wrapper.pl
Added drltrace frontend tool.
Changed drltrace's documentation.
> i#1349 build drltrace parallel to drstrace : frontend

- drltrace/CMakeLists.txt
Added initial exit-code-only test for drltrace.
> i#1960 drltrace tests: added initial exit-code-only test for drltrace

- umbra/umbra_x64.c
Windows 8.1 and higher have greatly expanded the pieces of the 64-bit
address space that they use, breaking the existing Windows 64-bit Umbra
shadow mapping scheme.  Fortunately a simple mask and displacement approach
still works, but we have to dynamically pick the shift and displacement
constants and segment sizes based on the Windows version.
Fixes #1810
> i#1810: add new shadow scheme for x64 windows 8.1+

- drltrace/CMakeLists.txt
- drltrace/drltrace.c
- drltrace/drltrace_frontend.cpp
Added printing of current thread id and return address for every called libcall.
Fixes #1949
> i#1949: printing id of current thread for drltrace

- drltrace/CMakeLists.txt
- drltrace/drltrace.c
- drltrace/drltrace_frontend.cpp
Added new test for library calls, arguments and ret addresses printing
Added new test for symargs printing
Fixed a bug when drltrace was not able to print in the console
> i#1960 add new drltace tests: arguments and ret value checks

- drsyscall/linux_defines.h
- tests/CMakeLists.txt
- tests/app_suite/CMakeLists.txt
- tests/memalign.c
- tests/memalign.pattern.res
- tests/memalign.res
- tests/operators.cpp
- tests/operators.out
- tests/operators.res
Fixes several warning and include issues with gcc 7.3.
Fixes #2099
> i#2099: fix build failures with gcc 7.3

- drsyscall/pdb2sysfile.cpp
- tests/CMakeLists.txt
- tests/runsuite_wrapper.pl
Pass -vv to get diagnostics on symbol fetch failures.
> i#2156: symbol fetch failures on Appveyor

- drmemory/frontend.c
Until DR supports the delay-load features needed for timezone
utilities used by dbghelp loading symbols, we work around a crash when
the "TZ" environment variable is unset by setting it.  This is a
transparency violation so we should remove this once DR's private
loader is improved.
Issue: #2164
> i#2164 timezone crash: Set TZ env var as workaround

- common/alloc.c
- common/alloc_replace.c
- drmemory/drmemory.c
- drmemory/frontend.c
- drmemory/leak.c
- drmemory/replace.c
- drmemory/syscall.c
- drstrace/drstrace.c
- drstrace/drstrace_frontend.c
- drsyscall/drsyscall_windows.c
- drsyscall/drsyscall_wingdi.c
- framework/samples/strace.c
- tests/app_suite/float_tests.cpp
- tests/app_suite/ntuser_tests_win.cpp
- tests/winthreads.c
- tools/winsyms.c
Fixes build warnings and gets the code to compile under VS2017.
Issue: #2250
> i#2250 VS2017: Fix build warnings

- drsyscall/linux_defines.h
Fixes a warning in the Android build.
> Fix Android build

- .appveyor.yml
Adds a missing artifact entry to deploy the .msi too.
Issue: #2255
> i#2255 Travis pkgs: Deploy .msi and .zip to Gibhut

- tests/runtest.cmake
On a failure to match either the stderr summary or individual results,
if the env var CI is set (true for Github Actions), runtest.cmake now
prints out the contents of the results file(s).  This greatly aids
remote debugging of CI failures.
Issue: #2334
> Print contents of results file on CI test failures

- .github/workflows/ci-package.yml
- .github/workflows/ci-windows.yml
Updates URLs to refer to the doxygen available from sourceforge.
> Arrange stale doxygen URLs

- .github/workflows/ci-aarchxx.yml
- .github/workflows/ci-clang.yml
- .github/workflows/ci-package.yml
- .github/workflows/ci-x86.yml
For Github Actions, we've seen stale apt state in VM's.
We proactively run update before every install.
> Add apt-get update step before every install

- .github/workflows/ci-docs.yml
Adds a Github Action script to generate the drmemory.org
web content.  This can't be tested on a branch, so this
will have to be merged and any fixes or fine-tuning done
separately.
Issue: #2260
> i#2260 web: Add automated web content generation

- .github/workflows/ci-package.yml
- CMakeLists.txt
Periodic official release: 2.4.0.
> Bump versions to 2.4.x

- drmemory/docs/download.dox
Updates the Download page with 2.4.0 release links.
> Add 2.4.0 section to the Download web page

- drmemory/docs/download.dox
Adds the build number 2 to the 2.4.0 links.
> Update 2.4.0 download links for build 2

- tests/addronly-reg.res
- tests/bitfield.strict.res
- tests/registers.blocklist.res
- tests/registers.pattern.res
- tests/registers.res
Updates DR to 0546c39d.
Updates test line numbers as asm_defines was changed.
Issue: #2417
> i#2417 Ubuntu20: Update DR

- .github/workflows/ci-package.yml
- CMakeLists.txt
- drmemory/docs/download.dox
- drmemory/docs/release.dox
Updates from 2.4.xx to 2.5.xx.
> Update to version 2.5.0

- README.md
fixes #2451 , might be related to #2444
> update drstrace link in README.md

- .github/workflows/ci-osx.yml
- CMakeLists.txt
- docs/Doxyfile.in
- drfuzz/drfuzz.dox
- drsyscall/table_macos_bsd.c
- tests/CMakeLists.txt
- tests/app_suite/CMakeLists.txt
Fixes build warnings with gcc 12.
Updates DR to 44312ad1c to fix gcc 12 issues there.
> Support gcc 12

- drmemory/docs/coverage.dox
> fix link to drcov documentation

- .github/workflows/ci-aarchxx.yml
- .github/workflows/ci-clang.yml
- .github/workflows/ci-docs.yml
- .github/workflows/ci-osx.yml
- .github/workflows/ci-package.yml
- .github/workflows/ci-windows.yml
- .github/workflows/ci-x86.yml
- CMakeLists.txt
- drltrace/CMakeLists.txt
- drltrace/drltrace.cpp
- drltrace/drltrace_frontend.cpp
- drltrace/drltrace_linux.config
- drltrace/drltrace_options.cpp
- drltrace/drltrace_options.h
- drmemory/docs/using.dox
- drsyscall/linux_defines.h
- drsyscall/table_linux.c
- make/git/devsetup.sh
- make/git/git_pullall.sh
> Update DR to the latest version

- .github/workflows/ci-package.yml
- CMakeLists.txt
- drmemory/docs/download.dox
- drmemory/docs/release.dox
Updates from 2.5.xx to 2.6.xx.
> Update to version 2.6.0

- drheapstat/drheapstat.c
- drsyscall/pdb2sysfile.cpp
Replaces a couple of INOUT missed by PR #2490.
> Replace remaining INOUT with DR_PARAM_INOUT

- .github/workflows/ci-package.yml
- .github/workflows/ci-windows.yml
Updates the PATH of our package build to find the new WIX version on the GA CI VM's.
Issue: DynamoRIO/dynamorio#6709
> Update WIX version to 6.14
