DynamoRIO/drmemory

drltrace/CMakeLists.txt, drltrace/README.md, drltrace/drltrace.c, drltrace/drltrace.dox, drltrace/runtest.cmake, license.txt
drltrace has been copied from dynamorio/clients/drltrace dir to
make further diffs easier and keep our working history clean.
NOTIFY's \n is replaced by NL macros to make runsuite.cmake happy.
=> i#1349 build drltrace parallel to drstrace: clean copy

drsyscall/table_macos_bsd.c
Explicitly define syscalls removed on Sierra to fix build error.
=> Fix build error on MacOS Sierra

drltrace/drltrace_frontend.cpp
Use drfront_appdata_logdir to handle situations when drltrace is
installed in a restricted dir (such as /usr/ or Program Files).
Fixes #1944
=> i#1944 use drfront_appdata_logdir interface

common/utils.c, drmemory/syscall_linux.c, drsyscall/drsyscall.c, framework/drmf_utils.c
Corrects uses of dr_safe_* that previously checked both the return value
and the size, as leaving the size parameter NULL is more efficient on
Windows 10 now due to kernel behavior changes.
=> DRi#2224: avoid asking for size from dr_safe_*

CMakeLists.txt, make/policies.cmake, tests/app_suite/CMakeLists.txt, tests/app_suite/fibers_win.cpp, tests/registers.c, tests/registers.res
Fixes 4 build failures:
1) Find dbghelp.dll when cmake is 64-bit.
2) Include the right header for SDK 8+ for app_suite/fibers_win.cpp.
3) Fix ml.exe "error A2" on tests/registers.c.
4) Fix build failures in namespace_tests_win.cpp.
Fixes #1952
=> i#1952: fix build failures with SDK 8.1 and 64-bit cmake

drmemory/frontend.c
Updates DR to the latest d747cc1 for DRi#1993's support for new
win10 pseudo-dlls.
Also adds ucrtbase.dll to the list of "usual dlls" to avoid complaining
about it on win10.
=> DRi#1993: update DR to handle recent win10 pseudo-dlls

drltrace/drltrace_frontend.cpp
Fix a bug related to incorrect usage of NULL_TERMINATED_BUFFER on a pointer instead of string.
Fixes #1959
=> i#1959: drltrace does incorrect parsing of logdir arg

drltrace/CMakeLists.txt
fix cmake references of non-existent target for drltrace
Fixes #1954
=> i#1954: drltrace cmake references non-existent target

drmemory/syscall_windows.c
Adds OP_test and OP_jne to the sanity check list of instructions we expect
to see in a system call wrapper, as they're used for Win10 x64 wrappers
since TH2.
Fixes #1968
=> i#1968: handle win10 x64 syscall sequences

drmemory/fastpath_x86.c
Some complex instrumentation sequences end up being too far for the
OP_jne_short used for the inheap_slot check for 64-bit shadow mode.  We
switch to a long jne here.
Fixes #1969
=> i#1969: use a long jne for inheap_slot instru

CMakeLists.txt
Fix a bug when cmake failed to find dbghelp.dll in case if no SDK
is installed (Windows 7/VS 2010)
Fixes #1956
=> i#1956: failed to find dbghelp.dll without SDK

drltrace/CMakeLists.txt, drltrace/drltrace.c, drltrace/drltrace_frontend.cpp, drsyscall/drsyscall.c
Added arguments printing of already known syscalls from drsyscall's
tables for Windows and Linux.
=> i#1948 add libcall args sym printing: syscall args support

drltrace/CMakeLists.txt, drltrace/drltrace.c
Implemented module id + offset printing scheme instead of
raw address for return addresses in drltrace.
Fixes #1979
=> i#1979: print module id + offset for ret addr in drltrace

drltrace/CMakeLists.txt
Added copy to device function to be able to execute drltrace test on Android.
Fixes #1972
=> i#1972: new drltrace test fails on android

CMakeLists.txt, common/utils.h, drltrace/CMakeLists.txt, drltrace/drltrace.cpp, drltrace/drltrace_frontend.cpp, drltrace/drltrace_options.h
Added droption usage instead of manual parsing in the drltrace client.
Added only_to_lib argument support in the drltrace_frontend.
Made only_to_lib case insensitive.
Drltrace is changed to be C++.
=> droption usage in the drltrace client

common/utils.h, drltrace/drltrace.cpp
Fixes error: invalid suffix on literal;
C++11 requires a space between literal and string macro `[-Werror=literal-suffix]`
Fixes #1990
------
Allows to compile drmemory with GCC 6.3
=> i#1990 C++11 requires space between literal and string macro

umbra/CMakeLists.txt
At one point, umbra.dll did not rely on libc. However, currently
multiple libc symbols are imported, and are thus not found by Umbra.  We
fix this by linking Umbra with libc.
Fixes #1993
=> i#1993 Umbra imports: Make Umbra import libc

CMakeLists.txt
Sets the linker options "/opt:ref /opt:icf /pdbcompress" globally to shrink
binary and pdb sizes on Windows.
=> DRi#2167 shrink pdbs: set space-saving linker options

.appveyor.yml
We remove VS2010 from Appveyor to speed it up (it does not parallelize
builds).  This means that we officially no longer support building with
VS2010.
=> DRi#2406 faster appveyor: drop VS2010 support

umbra/umbra.h
`umbra_insert_app_to_shadow()` destroys aflags. We add a reminder in the
documentation to save and restore aflags before we call this method.
=> Umbra docs: Adds note to umbra_insert_app_to_shadow

drltrace/CMakeLists.txt, drltrace/drltrace.config, drltrace/drltrace.dox, drltrace/drltrace_libcalls.cpp, drltrace/drltrace_options.cpp
Changed comment delimeter from ; to # in config file
Added config file copying on Android device
Fixed description of drltrace arguments for config file
=> i#1948 drltrace libcall args printing: android tests and config fix

drltrace/CMakeLists.txt
Added copying of config file on Android device.
Fixes #2001
=> i#2006: fixes drltrace test failures on Android

tests/CMakeLists.txt
Disables the kernel module test unless the generator is "Unix Makefiles" as
it assumes that "make" is in use.
Issue: #2019
=> i#2019 kernel mod test: disable for ninja

drmemory/alloc_drmem.c, drmemory/drmemory.c, drmemory/slowpath.c, drmemory/stack.c, drmemory/stack.h, drmemory/stack_x86.c, drmemory/syscall_linux.c
Adds 64-bit shadow-memory handling of stack operations in the slowpath (the
fastpath is NYI for 64-bit), including handling of the 128-byte UNIX ABI
stack redzone, which requires additional shadow writes to maintain the
shifted addressability boundary.
Issue: 111
=> i#111 x64: stack slowpath and redzone handling

drmemory/alloc_drmem.c, drmemory/fuzzer.c, drmemory/leak.c, drmemory/shadow.c, drmemory/shadow.h, drmemory/slowpath.c, drmemory/slowpath_x86.c, drmemory/syscall.c, tests/asmtest_x86.c, umbra/umbra_x64.c
Generalizes register shadow operations on the slowpath for 64-bit.
Widens the eflags shadow to be 2 bytes to match the other registers, for
ease of propagation.
Clears the top 32 bits of a GPR when the bottom 32 bits are written and
adds an explicit test of this to asmtest.
Skips shadow memory on the leak scan and supports 2-byte shadow value
searches in umbra x64 to get leaks working for x64 shadow.
Fixes a -verbose 5 bug from changes in 33e1c26.
This gets 64-bit tests/free working with -no_fastpath -no_esp_fastpath.
Issue: 111
=> i#111 x64: 64-bit shadow slowpath

common/alloc_replace.c, tests/cs2bug.cpp, tests/cs2bug.res, tests/cs2bug.wrap.res, tests/reachable.res
For C++ arrays, use size_t not int as the size of the array size field for
finding mismatches.
Fixes a cs2bug wart causing an extra error on x64.
Issue: 111
=> i#111 x64: heap mismatch generalization

drmemory/fastpath.h, drmemory/fastpath_x86.c, drmemory/optionsx.h, drmemory/shadow.c, drmemory/shadow.h, drmemory/stack.c, drmemory/stack_x86.c
Generalizes the full mode fastpath to handle 2-byte shadows and scratch
registers.  Defines the top 32 bits of 32-bit written registers.  Includes
numerous other miscellaneous fixes.
Some common instructions are not yet on the fastpath, including push and
pop.
Disables -share_xl8 for now for x64 (i#2025 covers getting to work).
Disables -esp_fastpath for now for x64 (i#2027 covers implementing it).
Does not yet enable tests: that is coming soon.
Issue: #111
=> i#111 x64: preliminary full mode fastpath support

drmemory/fastpath_x86.c, drmemory/optionsx.h, tests/addronly-reg.out, tests/addronly-reg.res
Due to the buggy i#1597 sub-dword xl8 sharing code and the complexity of
fixing it, disables xl8 sharing for sub-dword.
Updates the addronly-reg test template to show the now-visible 4th unaddr
error.
Goes further, given the i#2009 crash: disables xl8 sharing in general,
until we can re-evaluate and are sure no other crashes are caused by it.
Issue: #2032, #2009
=> i#2032 xl8 sharing: disable xl8 sharing for sub-dword and in general

CMakeLists.txt, drmemory/docs/release.dox, drmemory/drmemory.c, drmemory/optionsx.h, tests/CMakeLists.txt, tests/runtest.cmake
Changes 64-bit Linux to no longer have pattern mode be the default: instead
shadow-based full mode with uninitialized read checking is the default.
Windows is not quite ready for this yet.
Even on Linux we still have some major things like push, pop, and all esp
adjusts still on the slowpath.
Enables tests that were previously disabled for 64-bit.
Issue: 111
=> i#111 x64: enable 64-bit uninit read checking as default for Linux

tests/runsuite_wrapper.pl
The wrap_wincrt test is flaky and is failing often enough that we ignore
its failures for now.
Issue: #1741
=> i#1741 wrap_wincrt: mark test as flaky

common/alloc.c, drheapstat/drheapstat.c, drmemory/instru.c, drmemory/perturb.c
To fix immediate test errors due to poor interaction between global
auto-predication (introduced in dynamorio/dynamorio#1723) and meta
control flow, we pre-emptively opt out of auto-predication.
Fixes #2039
=> i#2039: Opts out of auto-predication

drsyscall/table_defines.h
Updates DR to bfef8b4 to fix several failures on Travis due to an upgrade
there.
Fixes additional compiler warnings from the Travis upgrade.
=> DRi#2641: fix failures on Travis

drmemory/fastpath_x86.c
Switches to using drutil_insert_get_mem_addr() instead of DrM's custom impl
(which was the inspiration for drutil, but had gotten out of sync).  This
fixes bugs in handling rip-rel memrefs.
Relies on the latest DR f6e8e1c for changes to drutil_insert_get_mem_addr()
that guarantee when an extra scratch reg is used.
Fixes #2041
=> i#2041: use drutil_insert_get_mem_addr()

common/alloc_replace.c, drmemory/alloc_drmem.c, drsyscall/drsyscall.c, drsyscall/drsyscall_windows.c, drsyscall/table_windows_ntoskrnl.c
Fixes several issues blocking full mode becoming the default on Windows
64-bit:
+ Replaced heap routines do not use stdcall.
+ get_sysparam_base() needs a one-slot adjustment.
+ There is padding between OBJECT_ATTRIBUTES fields.
+ A syscall param size stored in another field may be sub-pointer-sized.
+ NtQueryVirtualMemory's size fields are SIZE_T, not ULONG.
=> i#111 win64, part 1: syscall and native call updates

CMakeLists.txt, common/alloc.c, common/alloc.h, drheapstat/drheapstat.c, drmemory/alloc_drmem.c, drmemory/alloc_drmem.h, drmemory/drmemory.c, drmemory/instru.c, drmemory/spill.c
Adds use of DR's new kernel xfer events, eliminating the need to wrap the
Ki routines and watch several system calls.  Removes those events from the
alloc.h interface in favor of local kernel xfer events in the user.
Removes app signal handler tracking which is no longer needed.
Updates DR to fa465385.  Relaxes an assert triggered by DR's ea84da0
regarding handling displaced vsyscall code
=> DRi#241: use new kernel xfer events

drsyscall/table_windows_ntuser.c, wininc/ntuser.h
The memargs for NtUserGetCursorFrameInfo were incorrectly marked as IN when
they are actually OUT.
Issue: #487
=> i#487 NtUser syscalls: fix NtUserGetCursorFrameInfo memargs

.travis.yml
Skips running OSX for pull requests for now, since the Travis queue is
too long. We'll rely on the push to master to catch OSX issues and the
dev will have to revert or fix quickly at that point.
Re-writes the Travis build config from a matrix defined by os, compiler,
and env with exclusions to an explicit list of jobs, in order to use
conditional jobs. This is also clearer and easier to read.
=> DRi#2764 Travis OSX: skip OSX for PR's

.appveyor.yml, .travis.yml, CMakeLists.txt, tests/runsuite.cmake
Adds deployment of Travis and Appveyor-built zip packages to a fresh GitHub
Release following the scheme developed for DR.
=> DRi#1967 cron builds: Travis and Appveyor deployment

drmemory/client_per_thread.h, drmemory/drmemory.c, drmemory/fastpath.c, drmemory/fastpath.h, drmemory/instru.c, drmemory/optionsx.h, drmemory/slowpath.c, drmemory/slowpath.h, drmemory/spill.c
-single_arg_slowpath was never 100% robust, never the default, and its use
of decoding would likely have outweighted the performance gains from the
slimmer code cache footprint.  We remove it to simplify the code.
=> i#1795 drreg: cleanup: remove -single_arg_slowpath

drmemory/frontend.c
As a short-term workaround for x64 reachability problems with shadow tables
that are currently directly accessed with displacements, we add to the
default DR options "-no_vm_base_near_app".  Long-term we need to get a
local scratch register and load the table base into it, which will be much
easier with drreg (#1795).
Tested on both Windows with x64 full mode enabled and on Linux in a distro
where this assert is hit.
Issue: #2083
=> i#2083 x64 reach: put DrM lib in low mem

drmemory/fastpath_x86.c, tests/asmtest_x86.c
16-byte memrefs end up with long instrumentation sequences from
add_check_partial_undefined()'s list of shadow pattern possibilities.
We use a longer jump to avoid reachability issues.
Adds a test to asmtest.
Fixes #2118
=> i#2118: use long jump for 16-byte address checks

umbra/umbra.c, umbra/umbra_64.c
When scaling down, if we hit 0, we should bump up to 1.  Leaving at 0 leads
to an underflow in umbra_value_in_shadow_memory() which leads to a crash.
Fixes #2122
=> i#2122: fix shadow size underflow

umbra/umbra_32.c
Fixes overflow when setting protection for special block.
Fixes #2128
=> i#2128: Fix for umbra overflow in special block creation.

.travis.yml, CMakeLists.txt
The version split when we added 64-bit full mode to UNIX and released
it as 2.0.x before it was ready for Windows.  The cronbuilds were
using the 1.11.x Windows number so we could share the same Github
version, but that just caused (justifiable) confusion.  Here we bump
the version to 2.0 for UNIX but leave it at 1.11 for Windows, which
will result in different git tags and cronbuilds until we get Windows
up to 2.0.
=> Update non-Windows base version to 2.0

tests/addronly-reg.res, tests/bitfield.strict.res, tests/registers.blacklist.res, tests/registers.pattern.res, tests/registers.res
Updates DR to 191c479 to fix an error in
drfront_fetch_module_symbols() when loading 64-bit symbols.
Issue: #1848
=> i#1848 gensysnums: Fix x64 symbol fetch error

CMakeLists.txt, common/utils.c, common/utils.h, drmemory/frontend.c, drmemory/options.c, drmemory/options.h, drmemory/optionsx.h, drmemory/slowpath.h, drmemory/slowpath_arm.c, drmemory/slowpath_x86.c, drmemory/syscall.c, drsyscall/CMakeLists.txt, drsyscall/drsyscall.h, drsyscall/drsyscall_fileparse.c, drsyscall/drsyscall_windows.c, drsyscall/pdb2sysfile.cpp, framework/drmf_utils.c, make/resources.rc, tests/CMakeLists.txt, tests/runsuite_wrapper.pl
Moves the default syscall file location into logs/symbols instead of the
bin/ directory, as we need a writable location.  Adds a new option
-syscall_number_path to allow specifying a custom location.
Adds functionality to drsyscall to fetch debug info for system libraries
and parse every symbol in each library looking for syscall wrappers.  Two
interfaces are added: drsys_find_sysnum_dlls() and
drsys_generate_sysnum_file().  Includes usercall identification support via
a list of target wrappers for key usercalls plus interpolation between
known numbers to include speculative results for all usercalls.  The
syscall wrapper parsing code is based on DR's winsysnums.c, expanded to
support 64-bit.
The resulting syscall file only supports the current machine, unlike the
general files we have …
=> i#1848: auto-generate a syscall file on a new OS

CMakeLists.txt, drmemory/docs/release.dox, drmemory/frontend.c
Updates DR to dbccde9d for two features:
+ DRi#3391: dynamically identify APC CONTEXT offset, to fix an assert in
every app and crashes in apps with APC's on win10-1809.
+ The addition of drfront_set_verbose() which we now use here when
-v* is passed for symbol fetching diagnostics.
Issue: #2126, #1848
=> i#2126 win10-1809: Fix 32-bit crash

CMakeLists.txt, common/utils.c, common/utils.h, drmemory/drmemory.c, drmemory/frontend.c, drmemory/syscall.c
Updates DR to fae84d17 to retrieve the Windows build number, edition, and
release identifier.
Prints the new version information in the following places:
+ crash messages;
+ the win10 message about auto-generating syscall info for a new version;
+ results.txt;
+ global logfile.
Suppresses extra printing of DR Windows version warnings in debug build
from the frontend's use of DR standalone mode.
Asks the user to run "-debug -dr_debug" in release build crash messages.
Fixes #2127
=> i#2127: Add further Windows version info to diagnostics

drmemory/docs/release.dox, drmemory/drmemory.c, drmemory/optionsx.h, tests/CMakeLists.txt, tests/runtest.cmake
Updates the options, tests, and documentation for making full mode the
default for 64-bit Windows.
Issue: #111
=> i#111 win64: enable full mode by default for Windows 64

drmemory/docs/using.dox
Updates the documentation for VS2017 /debug flag changes and to remove
stale information about recommending building as 32-bit.
Fixes #2159
=> i#2159: Update docs for VS2017 and 64-bit

drmemory/options.c, drmemory/stack.c, tests/asmtest_x86.c
For x64 we do not yet have -esp_fastpath, but we want to support
-leaks_only.  It uses part of the -esp_fastpath path to run a stack
zeroing loop, but it does not actually need the -esp_fastpath gencode,
so we simply remove the option check and route to the fastpath
handler.
Issue: #111, #677
=> i#111 x64: support -leaks_only -no_esp_fastpath

CMakeLists.txt
We save significant space by not installing the static DR libraries.
This shrinks the Linux package from 120M down to 36M, and the Windows
zip and msi each shrink by 15M.
=> Do not install static DR libs

drsyscall/table_windows_ntoskrnl.c, wininc/ntexapi.h, wininc/ntioapi.h, wininc/ntmmapi.h
Adds several recent syscalls to eliminate false positives in the x64
procterm test on Windows.
Issue: #111
=> i#111 win64: Add recent syscall info for procterm test

drmemory/options.c, drmemory/optionsx.h, tests/CMakeLists.txt
Disables wrap-malloc tests as we do not support wrapping for 64-bit (i#2030).
Updates the redzone_size parameter to require 16-byte alignment
for 64-bit and changes the redzone8 test to redzone16 for 64-bit.
Issue: #111, #2030
=> i#111 x64: Disable tests not supported for 64-bit

drmemory/suppress-default.win.txt, tests/cs2bug.res, tests/registers.res, tests/runtest.cmake
Fixes a few of the failing 64-bit Windows full-mode tests:
+ Adds a default suppression for i#2170: what looks like a
real bug in RtlRestoreContext context copying.
+ Expands registers.res to match both rcx and ecx.
+ Expands runtest.cmake to handle nested %if in a .res file
for %if UNIX when %endif UNIX is used, for cs2bug.res.
Issue: #111, #2170
=> i#111 win64 tests: Fix several win64 tests

CMakeLists.txt
Adds two new CMake variables, DBGHELP_GLOB and SYMSRV_GLOB.  These are
added to the front of the search paths for dbghelp.dll and symsrv.dll.
This allows packaging to specify a glob for a prefered path for both
x86 and x64, which was not possible before.  This simplifies building
a package on a recent Windows version and having it work on an older
version.
=> Allow package.cmake to specify preferred dbghelp and symsrv paths

common/heap.c, drmemory/fastpath_x86.c, drmemory/slowpath_x86.c, drsymcache/drsymcache.c, drsyscall/drsyscall_windows.c, tests/rtl_memory_zones.c
Fixes the following win64 bugs:
+ Fixes the use of %l{d,u} instead of %z{d,u} in symcache and several
other places.  This caused the symcache files to never match,
causing delays and timeouts on some tests, especially those using
/MDd, due to DRi#2175.
+ Changes short jumps to long jumps in several fastpath locations to
avoid failures to reach due to longer x64 instructions.
+ Generalizes handling of OP_bswap which assumed a maximum size of 4
bytes.
+ Adds a workaround for DRi#3453 to avoid an assert with
-verify_sysnums.
Issue: #111
=> i#111 win64 tests: Fix more win64 tests

drmemory/alloc_drmem.c, drmemory/stack.c, drmemory/stack_x86.c, drmemory/suppress-default.win.txt, tests/operators.cpp, tests/operators.res, tests/runsuite_wrapper.pl
Fixes tests/operators taking forever on its OOM test by tweaking the
code to avoid compiler warnings on very large allocations.
Fixes x64 bugs in handle stack operations:
+ Handle DR rip-rel mangling when decoding from the cache on
the esp adjust slowpath.
+ Add an x64 chkstk pattern match.
Expands the i#2170 suppression to match ntdll.dll!RcConsolidateFrames.
Issue: #111, #2170
=> i#111 x64: Fix or suppress failing win64 tests

CMakeLists.txt
Updates the use of DBGHELP_GLOB and SYMSRV_GLOB from PR #2173 to avoid
using the wrong bitwidth, based on path name patterns.
=> Avoid using the wrong dbghelp bitwidth

.travis.yml, CMakeLists.txt, drmemory/docs/release.dox
Eliminates the split versioning for Windows vs Linux and updates the
base version to 2.1.0.  Updates the Travis git tag and changelist as
well.
=> Update base version to 2.1.0 for all platforms

umbra/umbra_32.c
Sets the `static_shadow_table_unused` flag to true to avoid using the same static instance upon multiple shadow table inits.
Fixes: #2199
=> Fixes multi init Umbra tables

tests/addronly-reg.res, tests/bitfield.strict.res, tests/registers.blacklist.res, tests/registers.pattern.res, tests/registers.res, tests/runsuite_wrapper.pl
Updates the line numbers of various asm-using tests after the DR
update in f1c8f7b.
Adds pcache-use (i#2202) and slowesp + noreplace-realloc (i#2178) to
the CI ignore list.
Issue: #2202, #2178
=> Get Travis and Appveyor green via suppression and line num fixes

drmemory/frontend.c
When running an application whose bitwidth doesn't match the frontend,
we launch the matching frontend, but we weren't propagating the exit
code back on Windows.  We fix that here.  Unfortunately it's not easy
to add a regression test since this requires a double-build.  Tested
manually.
Fixes #2206
=> i#2206: Propagate exit code from other-bitwidth frontend

drltrace/CMakeLists.txt, drltrace/drltrace.cpp, drltrace/drltrace_frontend.cpp, drltrace/drltrace_libcalls.cpp, drltrace/drltrace_options.cpp, drltrace/drltrace_options.h, drmemory/frontend.c, drmemory/syscall.c, drstrace/CMakeLists.txt, drstrace/drstrace.c, drstrace/drstrace_frontend.c, drsyscall/drsyscall.h, drsyscall/pdb2sysfile.cpp
Adds support for reading system call numbers from a text file to both
drstrace and drltrace.  Adds support for auto-generating that file,
just like is done in Dr. Memory.
Updates DR to 1713c2d2 to fix a decoder assert that breaks the
auto-generation.
Fixes #1983
=> i#1983: Add syscall auto-generation to drstrace and drltrace

drmemory/frontend.c, drmemory/shadow.c, drsyscall/drsyscall_macos.c, drsyscall/drsyscall_os.h, drsyscall/table_macos_bsd.c, tests/addronly-reg.res, tests/bitfield.strict.res, tests/registers.blacklist.res, tests/registers.pattern.res, tests/registers.res, tests/state.c, tests/state.pattern.res, tests/state.res, umbra/umbra_64.c
Updates DR to 5121dd0f for base 64-bit MacOS support from DR.
Updates the asm-using tests/*.res line numbers from DR asm_defines changes.
Updates the version check, system call numbers, and other miscellaneous
tweaks to get Dr. Memory building and running simple 64-bit apps on MacOS
in light mode (i#2083 blocks full mode).
Issue: #1438, #2083
=> i#1438 MacOS: Add 64-bit MacOS light mode support

drmemory/fastpath_x86.c, drmemory/frontend.c
Adds support for loading from shadow value comparison tables that cannot be
reached by a single 32-bit displacement.  To avoid needing another scratch
register, we instead use the top bits of the register holding the shadow
value, inserting the top 32 bits of the table address using a sequence
ror;or;ror, and then clearing after the comparison.
Fixes #2083
=> i#2083: Reference comparison tables above 2GB

drmemory/frontend.c, drmemory/shadow.c, drsyscall/drsyscall_macos.c, package.cmake
Fixes for 64-bit Mac full mode on small apps:
+ Updates DR to 704b750f to fix memquery performance and
release build warnings.
+ Pass "-signal_stack_size 64K" since the default seems too small.
+ Remove the BSD syscall number marker from the drsyscall table since
DR removes it from the numbers we see.
+ Updates package.cmake to build Mac 64_only.
Issue: #1438
=> i#1438 MacOS: 64-bit full mode support

common/callstack.c
Updates DR to 704b750f to fix memquery performance and
release build warnings (this was somehow omitted from a9800c4).
Fixes a crash that shows up with -brief on Mac64 but could happen anywhere:
callstack_next_retaddr() (called from check_type_match()) finds no frames
but tries to access them anyway, resulting in a null pointer deref.
Issue: #1438
=> i#1438 MacOS: Fix crash with zero callstack frames

drltrace/CMakeLists.txt, drmemory/frontend.c
Pulls in DR 0720551f for a fix to DRi#3886 where library segments have
sub-page alignment and are packed onto the same page on Catalina.
Updates the min supported Mac kernel to 19 (Catalina).
=> DRi#3886: Fix Catalina library segment alignment issue

.travis.yml, CMakeLists.txt, drltrace/CMakeLists.txt
Updates DR to af21cdc0 for decoder support for the AMD-specific
monitorx and mwaitx opcodes.
Fixes #2233
=> i#2233: Add AMD monitorx/mwaitx decode support

.travis.yml, CMakeLists.txt, common/utils_shared.c, docs/Doxyfile.in, drmemory/docs/errors.dox, drmemory/docs/light.dox, drmemory/docs/release.dox, drmemory/drmemory.c, umbra/umbra_64.c
Updates the version to 2.3.0.
Updates DR to 6d7e906d to fix DRi#4081: Mach-O indirect symbol lookup bug.
Tweaks Doxygen and a few files to build with clang 11.0 on Mac.
=> Release 2.3.0

drstrace/CMakeLists.txt
Extends the duplicate symbol handling in drstracelib to Ninja
generators as well.
Issue: #2250
=> i#2250 VS2017: Fix Appveyor VS2017 link error

drltrace/CMakeLists.txt, drstrace/CMakeLists.txt
Extends the i#1805 duplicate symbol handling to all generators.
Issue: #1805, #2250
=> i#2250 VS2017: Fix more link errors with duplicate symbols

.travis.yml
We need to check for both "type" and the TRAVIS_EVENT_TYPE env var in
the jobs matrix to support both scheduled and manually-triggered
package builds.
Issue: #2255
=> i#2255 Travis pkgs: Support scheduled or manual package builds

.travis.yml
Fixes an incorrect env var name for triggering our docs deployment.
Issue: #2260
=> i#2260 doc-deploy: Fix error in Travis config

tests/runsuite.cmake, tests/runsuite_wrapper.pl
Attempts to get Travis green by switching from 32-bit to 64-bit Mac
(we no longer support 32-bit) and adding currently flaky Linux tests
to the ignore list.
=> Switch to Travis Mac64 and ignore more failing tests

.travis.yml, CMakeLists.txt, common/alloc.h, common/alloc_replace.c, drmemory/alloc_drmem.c, drmemory/alloc_drmem.h, drmemory/annotations.c, drmemory/annotations_public.c, drmemory/annotations_public.h, drmemory/instru.c, drmemory/leak.c, drmemory/leak.h, drmemory/memlayout.c, drmemory/memlayout.h, tests/CMakeLists.txt, tests/memlayout.cpp, tests/memlayout.out, tests/memlayout.res, tests/runsuite_wrapper.pl, tests/runtest.cmake
Adds a new annotation DRMEMORY_ANNOTATE_DUMP_MEMORY_LAYOUT() which
triggers dumping the memory layout to a new file "memlayout.nnnn.log"
in the log subdirectory, where "nnnn" is incremented on each
successive dump.  The file is in JSON format.
Exports annotation support by building the required .c file with
custom flags as a library, and exports it and the two required header
files drmemory_annotations.h and dr_annotations_asm.h.
A basic block whose tag matches the address of the symbol "main" in
the executable is watched for.  Heap allocations prior to that point
are marked with a new flag MALLOC_BEFORE_MAIN.  The stack pointer at
that point is recorded.
At dump time, a heap iteration is done, skipping MALLOC_BEFORE_MAIN
objects.  Each object is placed into a tree.  Each thread stack is …
=> i#2266: Dump memory layout to json file on annotation

CMakeLists.txt, drfuzz/CMakeLists.txt, drltrace/CMakeLists.txt, drstrace/CMakeLists.txt, drsymcache/CMakeLists.txt, drsyscall/CMakeLists.txt, framework/samples/CMakeLists.txt, make/policies.cmake, make/rccheck.cmake, tests/CMakeLists.txt, umbra/CMakeLists.txt
Updates the minimum cmake to 3.7, matching DR.
Removes the settings of cmake policies CMP0053 and CMP0054 to OLD
since they do not affect the code at all.
Removes the setting of CMP0029 to OLD.  This only affects Qt and in a
minor way and we are not actively supporting the Qt visualizer
anymore.
Sets CMP0022 to NEW and
s/LINK_INTERFACE_LIBRARIES/INTERFACE_LINK_LIBRARIES/.  All other
needed changes have already been done as part of #1481.
Replaces all LOCATION property uses with generator expressions, except
for one tricky case with a user-specified DR dir.  Moves the CMP0026
setting of OLD to just that condition, avoiding it for normal uses
cases.  We may want to remove user-specified DR support in any case.
Fixes a warning about no parent scope for the recent annotation target.
Issue: …
=> i#2269 cmake: Eliminate cmake warnings

CMakeLists.txt, drsyscall/CMakeLists.txt, framework/drmf.cmake.in, framework/samples/CMakeLists.txt, make/policies.cmake
Removes the setting of CMP0024 to OLD.  Guards the inclusion of the
drmf export file in a new DrMemory_INTERNAL variable.
Adds a build-and-test test "drmf_proj" to ensure an external user can
build using our exported config files.
Fixes #1652
=> i#1652: Update CMake CMP0024 to modern behavior

.travis.yml, CMakeLists.txt, tests/CMakeLists.txt, tests/runsuite.cmake
DR does not support annotations on ARM (DRi#1672) so we have to
disable our annotations for non-x86.
Adds ARM and Android builds to Travis.
Issue: DynamoRIO/dynamorio#4168, DynamoRIO/dynamorio#1672
Fixes DynamoRIO/dynamorio#4168
=> DRi#4168: Annotations are not supported on ARM

tests/runtest.cmake
PR #2267 for #2266 commit af3a7927 broke the suppress-* tests by
adding a new parameter to runtest.cmake but not propagating it to the
sub-run for these tests.
=> Fix suppress test failure regression

tests/CMakeLists.txt, tests/cs2bug.light.out, tests/cs2bug.out, tests/reachable.out, tests/reachable.res, tests/runtest.cmake
cs2bug.cpp has slightly different results due to Travis compiler
upgrades.  We allow more variation in the output to get the cs2bug,
reachable, and malloc_callstacks tests green.
=> Relax precise error counts in cs2bug.cpp to fix Travis

drsyscall/linux_defines.h, drsyscall/table_linux.c
Adds SYS_prlimit64 to the Linux table.  This eliminates a false
positive running "ls" on newer distros.
Issue: #1019
=> i#1019 linux syscalls: Add prlimit64

tests/framework/CMakeLists.txt, tests/framework/drsyscall_client.c, tests/framework/strace_client.c
Adds use of a sysnum file generated by a prior Dr. Memory test to the
drmf tests which use dryscall.  #2279 covers a better long-term solution.
Fixes #2273
=> i#2273: Use sysnum file for drmf tests

tests/framework/umbra_client_allscales.c, umbra/umbra.c, umbra/umbra.h
Adds a new function umbra_get_granularity() which returns information about the granularity of an Umbra Map.
Issue: #2283
=> i#2283: Adds a method for retrieving granularity info about an Umbra Map.

.appveyor.yml, common/alloc.c, common/callstack.c, tests/runsuite.cmake
Updates DR to 1d711b47 and addresses a source compatibility change in
hashtable_config_t by setting the structure to zeroes.
Issue: #2285
=> i#2285: Update DR and drcontainers for compatibility change

CMakeLists.txt
Fixes a broken install step for ARM by disabling the annotation header
install for non-x86.  DR does not yet support annotations on ARM
(DRi#1672).
Issue: DynamoRIO/dynamorio#4168, DynamoRIO/dynamorio#1672
=> DRi#4168: Disable annotation header install for non-x86

drstrace/CMakeLists.txt
Adds /force:multiple to drstrace.exe to avoid VS2017 link errors.
Issue: #1805
=> i#1805 dup syms: Work around dup syms in drstrace.exe

CMakeLists.txt, common/callstack.c, common/callstack.h, drmemory/annotations.c, drmemory/memlayout.c, drmemory/memlayout.h, drmemory/report.c, tests/memlayout.cpp, tests/memlayout.out, tests/memlayout.res
Updates DR to 863a461c for dr_annotation_pass_pc().  Uses it to
acquire the PC for the current thread for the memory layout dump.
Adds callstack frames that overlap with the dumped stack to the layout
dump, with a pc, frame pointer, and function name for each.
Adds a function to tests/memlayout to test an additional frame.
Issue: #2266
=> i#2266 memlayout: Add callstack frames to layout dump

tests/framework/umbra_client_insert_app_to_shadow.c, umbra/umbra.h, umbra/umbra_32.c, umbra/umbra_64.c
Adds a new API function which allows the user to trigger the removal of redundant blocks that consist of only default values.
It is useful when low on memory.
Issue #2283
=> i#2283: Adds umbra_clear_redundant_blocks 

.appveyor.yml
The Doxygen 1.8.17 download path we use on Appveyor is now stale.  We replace it with 1.8.19.
=> Update Doxygen download path on Appveyor

CMakeLists.txt, CTestConfig.cmake
Adds dbghelp path updates for VS2017 and ctest submission updates for
CMake 3.14+.  These are part of PR #2265 but it is stuck on test
failures for updating Appveyor so we are applying its other changes
separately.
Issue: #2250
=> i#2250 VS2017: Update dbghelp and ctest logic

CMakeLists.txt, common/utils.c, drfuzz/CMakeLists.txt, drheapstat/visualizer/CMakeLists.txt, drltrace/CMakeLists.txt, drstrace/CMakeLists.txt, drsymcache/CMakeLists.txt, drsyscall/CMakeLists.txt, package.cmake, tests/CMakeLists.txt, tests/addronly-reg.res, tests/app_suite/CMakeLists.txt, tests/bitfield.strict.res, tests/framework/CMakeLists.txt, tests/fuzz/CMakeLists.txt, tests/nightly.cmake, tests/registers.blacklist.res, tests/registers.pattern.res, tests/registers.res, tests/runsuite.cmake, tests/runsuite_wrapper.pl, umbra/CMakeLists.txt
Updates DR to 24ba9f3 to pull in CMake 3.19 support which is required
after Github Actions upgrades.
Updates CMake code:
1) Raises the minimum version to 3.7 everywhere to avoid warnings.
2) Changes all absolute setting of COMPILE_DEFINITIONS to instead append,
since DR now puts its defines in that property.
=> DRi#4370: CMake 3.19 support

drmemory/suppress-default.win.txt
Adds RtlCaptureContext to the default Windows suppressions.  Errors
assumed to be false positives are showing up on Server 2016 and this
will help get our tests green.  We should investigate and improve our
CONTEXT handling to avoid needing this for a beter long-term solution.
Issue: #2333
=> i#2333: False positives in RtlCaptureContext

.github/workflows/ci-aarchxx.yml, .github/workflows/ci-clang.yml, .github/workflows/ci-osx.yml, .github/workflows/ci-x86.yml
Updates the Github Actions CI trigger to limit pushes to master and
add pull request open, reopen, and synchronize events.  This supports
PR's from forked repositories without adding duplicate triggers.
Issue: #2323
=> i#2323 GA CI: Change trigger to support forked repos

.github/workflows/ci-aarchxx.yml, .github/workflows/ci-clang.yml, .github/workflows/ci-osx.yml, .github/workflows/ci-windows.yml, .github/workflows/ci-x86.yml
Follows the lead of DynamoRIO/dynamorio#4585 and adds
auto-cancellation of a prior running job on a PR CI trigger.  Pushes
to master are never canceled.
Issue: #2323, DynamoRIO/dynamorio#4585
=> i#2323 GA CI: Add auto-cancellation of prior PR jobs

.github/workflows/ci-package.yml
First attempt to set up a package build.
Triggered via cron Fridays 9pm, or manually with a version input field.
Builds, creates a release with a tag, and posts the tarball.
Once we have the Linux x86 build working we can add the others.
Issue: #2323
=> i#2323 GA CI: Set up Linux package build

.github/workflows/ci-package.yml, tests/runsuite.cmake, tests/runsuite_wrapper.pl
Finishes the release package setup started in PR #2348.
Uses 3 parallel jobs to build 4 packages: Linux, Mac, and Windows zip+msi.
Each job uploads its binaries as an artifact, allowing sharing between jobs (having each
build job racily create and upload to a release failed: there is no check for an existing release).
Then a separate job waits for the 3 jobs to finish, creates a release (which includes adding
a tag), downloads the 4 artifacts, and uploads them to the release.
Tested via manual trigger which resulted in a successful tag and release: https://github.com/DynamoRIO/drmemory/releases/tag/release_2.3.18609-6
Issue: #2323
=> i#2323 GA CI: Add release package building and uploading

.github/workflows/ci-package.yml
Adds a step to the Linux package job to deploy the html documentation
to our Github Pages docs site.
Fixes: #2323
=> i#2323 GA CI: Deploy docs when posting a new release

.github/workflows/ci-package.yml, CMakeLists.txt
Fixes two problems with cronbuild versions:
+ The version was missing the major and minor: that was on the tag only.
+ The OSX version needs an additional computation to satisfy clang linker
restrictions.
Issue: #2323
=> i#2323 GA CI: Fix cronbuild version errors

.github/workflows/ci-package.yml
Adds a source checkout to the release job, needed to run "git log"
to compute the version.
Issue: #2323
=> i#2323: Fix cronbuild tag computation

common/alloc.c, drsymcache/drsymcache.c
Previously, for Linux drsymcache only checked the library file size to
determine whether the library had changed.  This led to bogus values
and subsequent false positives and worse problems.  Here we add an md5
computed over the first 1024 bytes of the mapped-in library as a
checksum.  It experimentally is enough to distinguish similar libc
versions (which have identical file sizes and top-level ELF headers).
Tested on Debian libc.so.6 2.31-5 vs 2.31-9.
Fixes #2356
=> i#2356: Add md5 of initial ELF bytes to drsymcache

drmemory/fastpath_x86.c, tests/asmtest_x86.c
Pulls scasq and cmpsq off the fast path to avoid an assert for load2x
with the 2nd operand 8 bytes.  Adding the fastpath support we'd like
long-term is under the general #111.
Adds test cases to asmtest, which reproduce the assert.
Fixes #2183
=> i#2183: Fix 8-byte load2x assert

common/alloc_replace.c, drmemory/annotations.c, drmemory/annotations_public.c, drmemory/annotations_public.h, drmemory/shadow.c, tests/CMakeLists.txt, tests/mmap.c, tests/mmap.out, tests/mmap.res
Fixes a bug where shadow_check_range() bypasses the shadow layer that
handles lazily-allocated shadow mappings and thus can crash.
Adds a test that reproduces the bug.
Adds a new DRMEMORY_ANNOTATE_MAKE_UNADDRESSABLE annotation to make it
easier to write the test.
Updates the allocator to use uint instead of ushort for its header's
request_diff field, as ushort is too small for a large allocation like
the one used in the test.  Since that affects the layout, goes ahead
and updates the prev_size_shr field to uint as well.
Fixes #2317
=> i#2317: Fix shadow_check_range() crash

tests/framework/CMakeLists.txt, umbra/umbra_64.c
Handles an app segment overlapping with a pre-defined umbra segment by
merging, instead of incorrectly adding a new alignment-expanded
segment that overlaps the pre-defined and causes failure.
Adds a test by setting DR's vm_base to force the overlap.
Fixes #1712
=> i#1712: Handle umbra segment overlap

drmemory/suppress-default.win.txt
Further analysis may show a programmatic solution, but for now we
auto-suppress to avoid tests failing on GA CI.
Issue: #2361
=> i#2361: Add NtContinue uninit to default suppressions

umbra/umbra_64.c
Checks for the vsyscall and if it is not present, removes the
0x7ff'ff4-0x7ff'ff8 gap from Umbra's mappings.  This then allows the
kernel or the app to map into the gap region, avoiding Umbra failures
in such circumstances.
Generalizes the Umbra region merging to also merge non-pre-defined
regions to handle the test added for #1712.
Tested by running tests/mmap in a loop, which found the original
problem.
The problem of vsyscall being present and the kernel mapping vdso into
the gap is left unsolved here.
Issue: #2363
=> i#2363 vsyscall: Remove umbra gap without vsyscall

common/alloc.c
The size_t type's mangled letter is m for 64-bit in the Itanium ABI
style.  We update the operator new mangled names for 64-bit to s/j/m/
here.  These are only used for distinguishing nothrow and placement,
not for locating operators, which may explain why there was no noticed
problem in the past.
=> Update mangled operator names for x64

common/callstack.c, drmemory/optionsx.h
Increases -callstack_max_scan from 2048 to 4096 to lower the
probability of not finding a frame, particularly with
-no_callstack_use_top_fp.  We need to scan 2408 bytes on my Linux
machine to find the ld-linux.so frame for the #1711 known-leak
suppression.
Fixes #2370
=> i#2370: Increase -callstack_max_scan from 2048 to 4096

tests/framework/CMakeLists.txt, tests/framework/umbra_client_faulty_redzone.c, tests/runsuite_wrapper.pl
Improves the time for testing faulty redzones.
The existing test tries to access a faulty redzone upon every memory access. However, the test only needs to test fault handling once. Therefore, the handling flag is checked to avoid unnecessary re-attempts. This improves the overall time of the test.
Fixes: #2341
=> i#2341: Improve time for Faulty Redzone Handling. 

tests/framework/CMakeLists.txt
Arranges the pass regex of framework tests to ensure that "TEST PASSED\n" is present at the end of the tests' outputs.
Fixes: #2377
=> i#2377: Arrange pass regex of add_drmf_test

tests/framework/umbra_client_faulty_redzone.c
Fixes a bug in the test for faulty red zones. The bug led the test to potentially calculate app addresses with scratch registers not containing their original values.
Issue: #2375
=> i#2375: Fix faulty redzone test

docs/Doxyfile.in
Removes the obsolete Doxyfile entry COLS_IN_ALPHA_INDEX.
=> Fix doxygen 1.9.1 build error

tests/addronly-reg.res, tests/bitfield.strict.res, tests/registers.blocklist.res, tests/registers.pattern.res, tests/registers.res
Updates DR to 795c8498 to bring in fix for
a drwrap crash which could affect Dr. Memory.
The DR update includes changes to asm_defines.asm,
which requires bumping Windows line numbers in some
test output patterns.
Issue: DynamoRIO/dynamorio#4607
=> Fix drwrap crash by updating DR

tests/leak_indirect.out, tests/leak_indirect.res, tests/runsuite_wrapper.pl
Adds umbra_client_faulty_redzone to the ignore list until it is fixed
(#2375).
Relaxes the leak_indirect output to keep it greener (#2367).
Issue: #2375, #2367
=> i#2375,i#2367: Ignore/improve flaky umbra and leak tests

drmemory/frontend.c
Adds a new static function file_is_executable in frontend.c
Fixes #2051
=> i#2051: in frontend, check for execute not read of DR root dir

.github/workflows/ci-clang.yml, .github/workflows/ci-package.yml, .github/workflows/ci-x86.yml
CMake 3.20 on GA CI fails to link 32-bit binaries, so we downgrade
our jobs to 3.19.7 for now.
Issue: DynamoRIO/dynamorio#4830
=> DRi#4830: Downgrade to CMake 3.19.7 to avoid 32-bit failures

umbra/umbra_64.c
Enables shadow memory tracking on AArch64.
This is a subsection of the larger ongoing AArch64 port of DRMemory.
Issue: #2016
=> i#2016: Port the umbra_64.c class to work on aarch64

.github/ISSUE_TEMPLATE/bug_report.md, CONTRIBUTING.md, README, README.md, docs/CMake_doxyfile.cmake, docs/Doxyfile.in, drmemory/docs/arm_port.dox, drmemory/docs/build.dox, drmemory/docs/contribute.dox, drmemory/docs/debugging.dox, drmemory/docs/design_docs.dox, drmemory/docs/download.dox, drmemory/docs/main.dox, drmemory/docs/new_release.dox, drmemory/docs/projects.dox, drmemory/docs/test.dox, make/git/git_review.sh
Adds all of the Github wiki content to new doxygen docs pages
integrated into the web site.
Updates references to wiki pages in other files in the repository.
Issue: #2260
=> i#2260 web: Add wiki content to doxygen docs

.github/workflows/ci-package.yml
The Mac build for an official release has a regression where
OSX_VERSION_NUMBER is not net.  We fix that here.
=> Fix error in official release step

.github/workflows/ci-package.yml
Include the build number in the Mac official release number.
=> Fix Mac release build number

.github/workflows/ci-aarchxx.yml, .github/workflows/ci-clang.yml, .github/workflows/ci-package.yml, .github/workflows/ci-x86.yml, drmemory/instru.c, drmemory/spill.c
Upgrades the VM used for our GA CI from 16.04, which is now
depcreated, to 20.04.
Fixes #2417
=> i#2417: Upgrade GA CI to Ubuntu 20.04

drmemory/alloc_drmem.c, drmemory/report.c
Fixes two failing tests on Ubuntu18+:
Adds a new string unaddr pattern where recent libc
reads a whole word beyond the allocated bounds.
This fixes a false positive in the loader test
on Ubuntu18+.
Fixes an uninitialized field tls_report_t.last_query_mod_start which
was failing the blocklist_uninit.op test.
Issue: #2417
=> i#2417 ubuntu20: Fix new libc unaddr and blocklist error

common/callstack.c
Extends PR #2424 to allow endbr64;jmp* for a PLT sequence on 64-bit.
Issue: #2417
=> i#2417 ubuntu20: Add endbr64 to PLT patterns

drsyscall/table_linux.c
Updates DR to f3d907d7 to fix DynamoRIO/dynamorio#5133: call
__libc_eary_init for private libc.  This fixes crashes in Dr. Memory
when it uses libc routines on glibc 2.32+..
Fills in the table entry for SYS_newfstatat to avoid false positives
from the loader's munmaps.
Fixes #2425
=> i#2425: Add Ubuntu21 support

.github/workflows/ci-package.yml, .github/workflows/ci-windows.yml
We're hitting problems downloading 1.7.2 and it's good to upgrade in
any case.  This udpates the ninja in our CI jobs to 1.10.2.
=> Upgrade GA CI ninja to 1.10.2

tests/framework/umbra_client_insert_app_to_shadow.c
Updates DR to 3b4d7485 which fixes DynamoRIO/dynamorio#4958,
eliminating basic blocks coming from the DR library.
This also pulls in a fix for an injection crash from app compatibility
layers: DynamoRIO/dynamorio#5198.
Removes the workaround in the umbra_client_insert_app_to_shadow test
that is now no longer needed.
Issue: DynamoRIO/dynamorio#4958, DynamoRIO/dynamorio#5198
=> DRi#4958: Update DR to eliminate DR blocks

README, README.md, drheapstat/drheapstat_frontend.c, drltrace/README.md, drmemory/frontend.c
Updates old links that pointed to drmemory.org/docs/
=> Fix stale doc links

.github/workflows/ci-aarchxx.yml
Mirrors the DynamoRIO/dynamorio#5527 fix by setting ANDROID_NDK_ROOT.
=> Fix Android CI build

tests/CMakeLists.txt, tests/framework/drsyscall_client.c, tests/suppress-genoffs.res, tests/suppress-gensyms.res, tests/suppress.c, tests/suppress.res
This patch edits tests/CMakeLists.txt to enable a selection of
existing tests for drmemory aarch64 as supported by the larger
initial aarch64 slowpath patch.
=> i#2016 AArch64: add initial testing for non-pattern mode

drsyscall/drsyscall.c, drsyscall/drsyscall.h, drsyscall/drsyscall_linux.c, drsyscall/table_defines.h, drsyscall/table_linux.c, drsyscall/table_linux_ioctl.c
Porting the drsyscall sub tool to AArch64 which is from the larger DrMemory port branch.
=> i2016 aarch64 drsyscall port

package.cmake, tests/runsuite.cmake
Updates DR to 1f40176ae to fix VS2019 warnings.
Issue: DynamoRIO/dynamorio#5767
=> Fix VS2019 warnings in drcachesim

drmemory/frontend.c
Adds bcrypt.dll to the allowlist of known libraries we expect to potentially see inside the drmemory.exe process.
Issue: #2498
=> i#2498 bcrypt init: Add bcrypt.dll to allowlist

.github/workflows/ci-clang.yml, .github/workflows/ci-package.yml, .github/workflows/ci-windows.yml, .github/workflows/ci-x86.yml
Switches from directly downloading from sourceforge, which was giving us 403 errors suddenly, to using
https://github.com/ssciwr/doxygen-install.
Updates jwlawson/actions-setup-cmake to v2.
Issue: DynamoRIO/dynamorio#7007
=> Fix doxygen and cmake install issues on runners

docs/Doxyfile.in
This causes the error
CMake Error at /tmp/dynamorio/drmemory/docs/CMake_doxyfile.cmake:256 (message):
/usr/bin/doxygen -u failed: This tag has been removed.
Tested:
$ make htmldocs
Fixes #2524
Fixes Dynamorio/dynamorio#7013
=> i#7013 build failure: Remove DOT_TRANSPARENT from Doxyfile.in

package.cmake
Updates DR to [a15656a0c](https://github.com/DynamoRIO/drmemory/pull/2527/commits/36a6d23d2c4048526613409e59cab6a0c72f1f91).
Replaces the AUTOMATED_TESTING set in package builds by PR #2474 with the new DISABLE_ZLIB CMake option added by
DynamoRIO/dynamorio#7030. This fixes a regression where msgbox_mask was set to 0 by default in packages, which caused many users to fail to obtain error information and has led to confusion with silent errors.
Tested:
Built https://github.com/DynamoRIO/drmemory/releases/tag/cronbuild-2.6.20005, unzipped it, and confirmed it pops up a message box by default on the machine where DynamoRIO/dynamorio#7024 is hit.
Fixes DynamoRIO/dynamorio#7025
=> Restore msgbox_mask package defaults

common/utils.h, common/utils_shared.c
The definition of strcasestr is
char *strcasestr(const char *text, const char *pattern);
but drmemory uses
const char *strcasestr(const char *text, const char *pattern);
This causes build errors when both /usr/include/string.h and common/utils.h are included in linux. The definition for strcasestr for C has always not had the `const` in the result type (going back to its original addition to glibc in 1997). Thus we're pretty safe in not breaking anything on *nix. The other main use case of drmemory's strcasestr is on Windows, which does not have strcasestr.
Tested:
$ cmake && make
Also, there are failures in the clang and x86 workflows, but comparing the logs before/after
shows all failures pre-exist this patch, no new failures.
Here is the complete audit, all failures are pre-existing. …
=> i#2522 strcasestr prototype error: Remove `const` from result type

tests/runsuite_wrapper.pl
Adds the 5 tests hitting an assert on 32-bit AMD machines, to get the suite green.  32-bit is lower priority and we have too few developers unfortunately to root-cause and fix this.
Issue: #2491
=> i#2491: Ignore AMD 32-bit-assert test failures for now

drmemory/docs/build.dox, drmemory/docs/new_release.dox, tests/runsuite.cmake
Updates DR to the latest a09c4c9f5a0503aaa4efc2c9d59aada92de85291 to pull in the fix for DynamoRIO/dynamorio#7253 to avoid submodule issues with elfutils from sourceware.org.
=> Update DR to latest to fix elfutils issue

drfuzz/drfuzz_mutator.c
In previous Cppcheck versions (like 2.8 and earlier) there were some warnings about uninitialized variables. This is easily fixed by trivial initialization with zero. In the new versions of Cppcheck these warnings does not arise, because, the init occurs in another place of the code and new Cppcheck versions can handle it.
But the created commit will still be useful for improving the quality of the code.
**Before:**
```
❯ ./cppcheck --version
Cppcheck 2.8
❯ ./cppcheck /Projects/drmemory/drfuzz/drfuzz_mutator.c
Checking /Projects/drmemory/drfuzz/drfuzz_mutator.c ...
/Projects/drmemory/drfuzz/drfuzz_mutator.c:228:32: error: Uninitialized variable: actual_size [uninitvar]
if (!res || map == NULL || actual_size < map_size) {
^
/Projects/drmemory/drfuzz/drfuzz_mutator.c:220:11: note: Assuming …
```
=> i#1928: Fix cppcheck warning about uninitialized variable

drmemory/slowpath_x86.c
Among the conditions in return statement were identical ones, which is a simple typo. The solution is a removal of unnecessary repetitions.
**Before:**
```
return (opc_is_stringop_loop(opc) ||
opc == OP_ins || opc == OP_outs || opc == OP_movs ||
opc == OP_stos || opc == OP_lods || opc == OP_cmps ||
opc == OP_cmps || opc == OP_scas || opc == OP_scas);
```
**After:**
```
return (opc_is_stringop_loop(opc) ||
opc == OP_ins || opc == OP_outs || opc == OP_movs ||
opc == OP_stos || opc == OP_lods || opc == OP_cmps ||
opc == OP_scas);
```
Fixes #2190
=> i#2190: Fix a typo of identical conditions

drsyscall/drsyscall_linux.c
The code changes involve updating the handling of the arg variable, which is used in the handle_semctl function to represent the semun union argument passed to the semctl system call. The main change is to dereference a pointer to the arg variable instead of using a direct structure assignment.
Fixes #2478
=> i#2478: Fix Compilation error on linux mint 21.1 

CMakeLists.txt
Fixes a build error with newer toolchains (showed up at https://github.com/DynamoRIO/dynamorio/actions/runs/14320843017/job/40137266370) where we need `-march=armv7-a+fp` to avoid an error "‘-mfloat-abi=hard’: selected architecture lacks an FPU".
Issue: DynamoRIO/dynamorio#7270, DynamoRIO/dynamorio#5299
=> Add +fp to armv7 arch to fix build error

drsyscall/table_windows_ntoskrnl.c
This pull request updates `drsyscall/table_windows_ntoskrnl.c` to include correct minimum and maximum Windows versions for several syscalls.
These changes were generated via a script (with the help of j00ru with the actual [x86 syscall tables](https://j00ru.vexillium.org/syscalls/nt/32/)) so their might be a minor inaccuracy or two, but overall it should be correct, this update should have no functional impact on Dr. Memory's behavior.
**Note:** Due to the current absence of specific macros in Dr. Memory that precisely define every Windows service pack or update, some entries might use broader version ranges. For instance, if you see an entry like `(WINVISTA,WINVISTA)`, please interpret this as the syscall being present from the initial release of Windows Vista (SP0) up to its final …
=> Update windows syscall table with the correct min/max versions

drsyscall/table_windows_ntuser.c, wininc/ntuser.h
This pull request updates the definition for `NtUserOpenClipboard` to reflect that the syscall writes to a pointer provided in the second argument. `OpenClipboard` passes an address of a local variable to this parameter and then reads from it, causing the following warning:
```
Error #1: UNINITIALIZED READ: reading 0x00000092296ff998-0x00000092296ff99c 4 byte(s)
Note: @0:00:00.082 in thread 11352
Note: instruction: cmp    0x38(%rsp) $0x00000000
```
Similar changes would apply to the following files in the dynamorio submodule; not sure if you want me to create a separate pull request to address that:
```
dynamorio\ext\drsyscall\table_windows_ntuser.c
dynamorio\ext\drmf\wininc\ntuser.h
```
=> Fix NtUserOpenClipboard

.github/workflows/ci-aarchxx.yml, .github/workflows/ci-clang.yml, .github/workflows/ci-docs.yml, .github/workflows/ci-package.yml, .github/workflows/ci-windows.yml, .github/workflows/ci-x86.yml, common/alloc_replace.c, drsyscall/drsyscall.c, tests/runsuite_wrapper.pl
Updates Github Actions (GA) jobs from ubuntu-20 to ubuntu-22 and from windows-2019 to windows-2022.
Updates DR to f233a38f9 to pull in DR's Ubuntu22 and VS2022 fixes.
Fixes #2560
Fixes #2548
=> i#2560,#2548: Update to ubuntu22 and vs2022 GA platforms
